basic_app/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'basic_app'
urlpatterns = [

    url(r'^index',views.index,name='index'),
    url(r'^login/',views.user_login,name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'tenant',views.tenantView, name='tenantView'),
    url(r'^managerLogin',views.manager_login,name='managerLogin'),
    url(r'^manager',views.manager,name='manager'),
    url(r'^welcomeManager',views.welcomeManager,name='welcomeManager'),
    # url(r'^delete/(?P<username>[A-Za-z]+)$', views.delete_tenant, name='delete'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),
    url(r'^$', views.index, name='home'),
    url(r'^special', views.special, name='special'),
    url(r'^logout',views.user_logout, name='logout'),



]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone


# Create your model with the extra fields needed.
class UserProfileInfo(models.Model):
    # create a relationship with the user model*do not inherit
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    # Add additional attributes
    Number = models.IntegerField(default=20)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User


# base form
class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password', ]


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        # fields = ['roomNumber', ]
        fields = ['Number']

basic_app/views.py
from django.shortcuts import render, redirect
from basic_app.forms import UserProfileInfoForm, Userform
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from basic_app.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


# make the index view
def index(request):
    return render(request, 'index.html')


def tenantView(request):
    return render(request, 'tenant view.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


@login_required
def special(request):
    return HttpResponse("You are logged In")


# make the registration view
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = Userform(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # then here you can harsh
            user.set_password(user.password)
            # then can save again
            user.save()

            profile = profile_form.save(commit=False)
            # then set the one to one relationship between user form and user info form
            profile.user = user
            registered = True

    # if there was nothing submitted, render the form as blank to be refilled
    else:
        user_form = Userform()
        profile_form = UserProfileInfoForm()

    return render(request, 'register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}
                  )


def user_login(request):
    if request.method == 'POST':
        user_name = request.POST.get('username')
        password = request.POST.get('password')
        # after grabbing the fields we need to autheticate
        user = authenticate(username=user_name, password=password)
        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse('basic_app:tenantView'))

            else:
                return HttpResponse("your account is not active")
        else:
            return HttpResponse('Invalid log in details')
    else:
        return render(request, 'login.html', {'login': login})


def manager_login(request):
    if request.method == 'POST':
        user_name = request.POST.get('username')
        password = request.POST.get('password')
        # after grabbing the fields we need to autheticate
        user = authenticate(username=user_name, password=password)
        if user:
            if user.is_staff:
                login(request, user)

                return HttpResponseRedirect(reverse('basic_app:welcomeManager'))

            else:

                return HttpResponse("YOU ARE NOT A REGISTERED USER")
        else:
            return HttpResponse('Invalid log in details')
    else:
        return render(request, 'login.html', {'login': login})


def welcomeManager(request):
    return render(request, 'welcomeManager.html')


def manager(request, ):
    user_list = User.objects.all()
    return render(request, 'manager.html', {'user_list': user_list})


# def delete_tenant(request, pk):
#     tenant_list = User.objects.get(username=pk)
#     tenant_list.delete()
#     messages.success(request, 'item removed')
#     return redirect('manager.html')

templates/base.html
{% load staticfiles %}
{% csrf_token %}
      <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css"  media="screen,projection"/>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link type="text/css"  rel="stylesheet" href="{% static 'resources/css/styles.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


<nav class="cyan darken-4">
    <div class="nav-wrapper">
        <a href="{% url 'basic_app:index' %}" class="brand-logo" style="color: sandybrown">
            <i class="material-icons" >home</i>RMS</a>
<nav class="cyan darken-4">
    <div class="nav-wrapper">
      <a href="{% url 'basic_app:index' %}" class="brand-logo" style="color: sandybrown"><i class="material-icons" >home</i>RMS</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <li><a name="manager" class="btn waves-effect waves-red" style="background-color:sandybrown;color: black" href="{% url 'basic_app:managerLogin' %}">MANAGER</a></li>
        <li><a name="tenant" class="btn waves-effect waves-red" style="color: black" href="{% url 'basic_app:login' %}">TENANT</a></li>
      </ul>
    </div>
    <ul class="sidenav" id="mobile-demo" style="background-color: orange">
    <li><a href="{% url 'basic_app:managerLogin' %}">MANAGER</a></li>
    <li><a href="{% url 'basic_app:login' %}">TENANT</a></li>
  </ul>
</nav>

<script type="text/javascript" rel="script" src="{% static 'resources/js/materialize.min.js' %}"></script>
<script type="text/javascript" rel="script" src="{% static 'resources/js/jquery-3.3.1.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
<script type="text/javascript" rel="script" src="{% static 'resources/js/move.js' %}"></script>

        <script>
                $(document).ready(function(){
            $('.sidenav').sidenav();
          });

        </script>

{% block content %}

{% endblock %}

templates/index.html
<title>Home</title>
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<body style="background-color:darkslategray;">
    <br>
<div class="slider" >
    <ul class="slides" style="height: 100%">
      <li>
        <img src="{% static 'resources/images/condominiums.jpg' %}"> <!-- random image -->
        <div class="caption center-align">
          <h3 style="color: orange">RENT MANAGEMENT SYSTEM</h3>
            <h5 style="color: white"><i>No worries More Gain</i></h5>
        </div>
      </li>
{#      <li>#}
{#        <img src="{% static 'resources/images/white scrapper.jpeg' %}"> <!-- random image -->#}
{#        <div class="caption left-align">#}
{#          <h3 style="color: orange">NO WORRIES</h3>#}
{#          <h5 class="light grey-text text-lighten-3">Quit worries about your rent management</h5>#}
{#        </div>#}
{#      </li>#}
      <li>
        <img src="{% static 'resources/images/courtyard.jpeg' %}"> <!-- random image -->
        <div class="caption right-align">
          <h3 style="color: orange">TENANTS</h3>
          <h5 class="light grey-text text-lighten-3"> Can discuss and get information on their rent plans </h5>
        </div>
      </li>
      <li>
        <img src="{% static 'resources/images/white scrapper.jpeg' %}"> <!-- random image -->
        <div class="caption center-align">
          <h3 style="color: orange">MANAGERS</h3>
          <h5 class="light grey-text text-lighten-3">Easily and efficiently managing rentals and apartments</h5>
        </div>
      </li>
    </ul>
</div>
<div style=" padding-left: 600px">
<ul>
    <li>QUICK LINKS</li>
    <li><a href="{% url 'basic_app:login' %}" style="color: orange">Login as Tenant</a></li>
    <li><a href="{% url 'basic_app:managerLogin' %}"style="color: orange">Login as Manager</a></li>
</ul>

</div>



<script>
    $(document).ready(function(){
      $('.slider').slider();
    });
</script>





{% endblock %}
</body>

templates/login.html
<title>Login</title>
{% extends 'base.html' %}
{% block content %}
    <body style="background-color:cadetblue" >
    <div style="width: 800px;padding-left: 300px">
    <h2>Please Login</h2>
        <form action="" method="POST">
            {% csrf_token%}
            <span><label style="font-size: 30px;color: black">Username</label></span>
            <input type="text" name="username" placeholder="Username">
            <span><label style="font-size: 30px;color: black">Password</label></span>
            <input type="password" name="password" placeholder="password">
            <input type="submit" value="LOGIN">
{#            <div>Do not have an Account?<span><a href="{% url 'basic_app:register' %}">  Create an Account</a></span></div>#}
        </form>


    </div>

</body>
{% endblock %}

templates/manager.html
{% extends 'base.html' %}
{% block content %}
     <div style="padding-right:70px;padding-left:100px">
        <div style="width: 1000px;padding-left: 90px;padding-right: 90px;background-color: darkslategray">
        {% if user_list %}
            <p style="font-size: 30px;padding-left: 200px;padding-right: 200px">TENANT LIST</p>
         {% for user in user_list %}
             <div style="padding-left: 90px; background-color: beige">
                <p>Username:{{ user.username }}</p>
                <span>email:{{ user.email }}</span>
    {#                <td>{{ things.time }}</td>#}
    {#                <td>{{ things.completed }}</td>#}
    {#            <span><a href="{% url 'delete' user.username %}">remove</a></span>#}
                <div class="divider"></div>
             </div>

         {% endfor %}
        {% else %}
            <h4>cant find this</h4>
        {% endif %}
        </div>
     </div>
{% endblock %}

templates/managerLogin.html
<title>Login</title>
{% extends 'base.html' %}
{% block content %}
    <div>
    <h2>Please Login</h2>
        <form action="" method="POST">
            {% csrf_token%}
            <input type="text" name="username" placeholder="Username">
            <span><label style="font-size: 15px;">Password</label></span>
            <input type="password" name="password" placeholder="password">
            <input type="submit" value="LOGIN" >
            <div>Do not have an Account?<span><a href="{% url 'basic_app:register' %}">  Create an Account</a></span></div>
        </form>
    </div>
{% endblock %}

templates/register.html
<title>Register</title>

{% extends 'base.html' %}
{% block content %}
<body style="background-color: darkslategray">
<div class="select2-container" style="padding-left: 200px">
    <div class="registerForm" style="width: 800px;padding:80px;background-color:beige">
        {% if registered %}
            <h1 style="width:1000px;color: orange;">Thank you for registering</h1>
        {% else %}

            <h5>Simply fill out the form to register a tenant</h5>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <br>
            <input type="submit" value="register" >
            </form>
        {% endif %}
    </div>
{% endblock %}
</div>
</body>

templates/tenant view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}


<body style="background-color: darkslategray">
    <div class="slider" >
        <ul class="slides" style="height: 100%">
          <li>
            <img src="{% static 'resources/images/whitewall.jpeg' %}" style="width: 100%; height: 100%">
            <div class="caption center-align">
              <h3 style="color: orange">WELCOME <span style="color: darkslategray;">{{ user.username }}</span> </h3>
                <span style="color: black">email:{{ user.email }}</span>

            </div>
          </li>
            <li>
            <img src="{% static 'resources/images/white1.jpeg' %}" style="width: 100%; height: 100%">
            <div class="caption center-align">
              <h3 style="color: orange">WELCOME <span style="color: darkslategray;">{{ user.username }}</span> </h3>
                <span>email:{{ user.email }}</span>
            </div>
          </li>
        </ul>
    </div>


    <script>
    $(document).ready(function(){
      $('.slider').slider();
    });
    </script>


{% endblock %}
</body>

templates/tenant.html
{% extends 'base.html' %}
{% block content %}
    <div style="width: 500px;padding-left: 50px">
    {% if user_list %}
     {% for user in user_list %}

            <p>Username:{{ user.username }}</p>
            <span>email:{{ user.email }}</span>
{#                <td>{{ things.time }}</td>#}
{#                <td>{{ things.completed }}</td>#}

     {% endfor %}
    {% else %}
        <h4>cant find this</h4>
    {% endif %}
    </div>

{% endblock %}o %}

templates/welcomeManager.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content%}

 <div>
      <body style="background-color: darkslategray">
      <div class="fixed-action-btn">
          <a class="btn-floating btn-large red">
            <i class="large material-icons">dehaze</i>
          </a>
          <ul>
            <li><a class="btn-floating red"   href="{% url 'basic_app:register' %}"><i class="material-icons">add_circle_outline</i></a></li>
            <li><a class="btn-floating yellow darken-1" href="{% url 'basic_app:manager' %}"><i class="material-icons">assignment</i></a></li>

          </ul>
        </div>
    <div class="slider" >
        <ul class="slides" style="height: 100%">
          <li>
            <img src="{% static 'resources/images/manyhouses.jpeg' %}" style="width: 100%; height: 100%">
            <div class="caption center-align">
              <h3 style="color: darkslategrey">WELCOME MANAGER<span style="color: orange;">{{ user.username }}</span> </h3>
                <span style="color: black">email:{{ user.email }}</span>

            </div>
          </li>
            <li>
            <img src="{% static 'resources/images/couch.jpeg' %}" style="width: 100%; height: 100%">
            <div class="caption center-align">
              <h3 style="color: black"> WELCOME MANAGER <span style="color: orange;">{{ user.username }}</span> </h3>
                <span style="color: black">email:{{ user.email }}</span>
            </div>
          </li>
        </ul>
    </div>




    <script>
            $(document).ready(function(){
        $('.fixed-action-btn').floatingActionButton();
        $('.slider').slider();
      });

    </script>
{% endblock %}